import type { Metadata } from "next";
import { getMetadata, siteConfig } from "@repo/config";
import { LegalPageTemplate, type LegalSection } from "@/components/marketing/legal-page-template";

export const metadata: Metadata = getMetadata({
  title: "Acceptable Use Policy",
  description: `Acceptable Use Policy for ${siteConfig.name} - Learn about permitted and prohibited uses of our URL shortening service.`,
});

const sections: LegalSection[] = [
  { id: "purpose", title: "1. Purpose", icon: "Target" },
  { id: "scope", title: "2. Scope", icon: "FileCheck" },
  { id: "prohibited-content", title: "3. Prohibited Content", icon: "Ban" },
  { id: "prohibited-activities", title: "4. Prohibited Activities", icon: "ShieldAlert" },
  { id: "link-scanning", title: "5. Link Scanning", icon: "Eye" },
  { id: "spam-policy", title: "6. Spam Policy", icon: "AlertTriangle" },
  { id: "fair-use", title: "7. Fair Use", icon: "Scale" },
  { id: "enforcement", title: "8. Enforcement", icon: "Shield" },
  { id: "reporting", title: "9. Reporting Abuse", icon: "Flag" },
  { id: "appeals", title: "10. Appeals Process", icon: "RotateCcw" },
  { id: "contact", title: "11. Contact Us", icon: "Mail" },
];

export default function AcceptableUsePage() {
  const productName = siteConfig.name;
  const contactEmail = siteConfig.email;
  const lastUpdated = "January 15, 2026";
  const effectiveDate = "February 1, 2026";

  return (
    <LegalPageTemplate
      title="Acceptable Use Policy"
      lastUpdated={lastUpdated}
      effectiveDate={effectiveDate}
      sections={sections}
    >
      {/* Section 1: Purpose */}
      <section id="purpose">
        <h2>1. Purpose</h2>
        <p>
          This Acceptable Use Policy (&quot;AUP&quot;) defines the rules governing the use of
          {productName} (the &quot;Service&quot;). The purpose of this policy is to:
        </p>
        <ul>
          <li>Protect our users, their end users, and the broader internet community</li>
          <li>Maintain the security, reliability, and reputation of our Service</li>
          <li>Ensure compliance with applicable laws and regulations</li>
          <li>Preserve the trust that users place in shortened links</li>
        </ul>
        <p>
          This AUP is incorporated into and forms part of our <a href="/terms">Terms of Service</a>.
          Violations of this policy may result in suspension or termination of your account.
        </p>
      </section>

      {/* Section 2: Scope */}
      <section id="scope">
        <h2>2. Scope</h2>
        <p>This policy applies to all users of {productName}, including:</p>
        <ul>
          <li>All shortened links created through our Service</li>
          <li>QR codes generated by our Service</li>
          <li>Custom domains connected to our Service</li>
          <li>API usage and integrations</li>
          <li>Any content or destinations linked through our Service</li>
        </ul>
        <p>
          You are responsible for ensuring that your use of the Service, including all content you
          link to, complies with this policy.
        </p>
      </section>

      {/* Section 3: Prohibited Content */}
      <section id="prohibited-content">
        <h2>3. Prohibited Content</h2>
        <p>You may not use {productName} to create links to content that:</p>

        <h3>3.1 Malware &amp; Security Threats</h3>
        <ul>
          <li>Contains viruses, trojans, worms, or other malicious software</li>
          <li>Attempts to install unwanted software on users&apos; devices</li>
          <li>Exploits security vulnerabilities or performs drive-by downloads</li>
          <li>Contains ransomware or cryptomining code</li>
        </ul>

        <h3>3.2 Phishing &amp; Fraud</h3>
        <ul>
          <li>Impersonates other websites, companies, or individuals</li>
          <li>Attempts to steal login credentials, financial information, or personal data</li>
          <li>Conducts advance-fee fraud, lottery scams, or similar schemes</li>
          <li>Creates fake login pages or credential harvesting sites</li>
        </ul>

        <h3>3.3 Illegal Content</h3>
        <ul>
          <li>
            Child sexual abuse material (CSAM) -{" "}
            <strong>immediate account termination and report to authorities</strong>
          </li>
          <li>Content that violates applicable laws in any jurisdiction</li>
          <li>Facilitates illegal drug trafficking</li>
          <li>Sells counterfeit goods or pirated content</li>
          <li>Promotes or facilitates human trafficking</li>
          <li>Provides instructions for creating weapons or explosives</li>
        </ul>

        <h3>3.4 Violence &amp; Harmful Content</h3>
        <ul>
          <li>Promotes terrorism or violent extremism</li>
          <li>Contains credible threats of violence against individuals or groups</li>
          <li>Glorifies or incites violence</li>
          <li>Contains graphic violence intended to shock or disturb</li>
          <li>Promotes self-harm or suicide</li>
        </ul>

        <h3>3.5 Hate Speech &amp; Harassment</h3>
        <ul>
          <li>
            Promotes hatred against individuals or groups based on race, ethnicity, religion,
            gender, sexual orientation, disability, or other protected characteristics
          </li>
          <li>Contains content intended to harass, bully, or intimidate individuals</li>
          <li>Doxes or shares private information without consent</li>
        </ul>

        <h3>3.6 Deceptive Content</h3>
        <ul>
          <li>Misleads users about the destination or nature of the link</li>
          <li>Uses deceptive redirect chains to hide the final destination</li>
          <li>Spreads disinformation or dangerous medical misinformation</li>
          <li>Employs cloaking to show different content to users vs. our scanners</li>
        </ul>

        <h3>3.7 Intellectual Property Violations</h3>
        <ul>
          <li>Infringes copyrights, trademarks, or other intellectual property rights</li>
          <li>Distributes pirated software, media, or other copyrighted materials</li>
          <li>Circumvents digital rights management (DRM) protections</li>
        </ul>
      </section>

      {/* Section 4: Prohibited Activities */}
      <section id="prohibited-activities">
        <h2>4. Prohibited Activities</h2>
        <p>In addition to prohibited content, the following activities are not allowed:</p>

        <h3>4.1 Service Abuse</h3>
        <ul>
          <li>Creating automated accounts or links in violation of our terms</li>
          <li>Attempting to circumvent rate limits or usage restrictions</li>
          <li>Using bots or automated tools without authorization</li>
          <li>Sharing or selling access to your account</li>
          <li>Creating accounts after being banned</li>
        </ul>

        <h3>4.2 Security Violations</h3>
        <ul>
          <li>
            Attempting to gain unauthorized access to our systems or other users&apos; accounts
          </li>
          <li>Probing, scanning, or testing the vulnerability of our systems without permission</li>
          <li>Interfering with or disrupting the integrity or performance of our Service</li>
          <li>Attempting to reverse engineer, decompile, or extract source code</li>
        </ul>

        <h3>4.3 Network Abuse</h3>
        <ul>
          <li>Generating artificially inflated click counts or analytics data</li>
          <li>Using the Service for click fraud or ad fraud schemes</li>
          <li>Creating links designed to manipulate search engine rankings</li>
          <li>Using our infrastructure for denial-of-service attacks</li>
        </ul>

        <h3>4.4 Privacy Violations</h3>
        <ul>
          <li>Collecting personal data through links without proper consent</li>
          <li>Using tracking features in ways that violate privacy laws</li>
          <li>Sharing analytics data in violation of data protection regulations</li>
        </ul>
      </section>

      {/* Section 5: Link Scanning */}
      <section id="link-scanning">
        <h2>5. Link Scanning &amp; Detection</h2>
        <p>We employ multiple layers of automated and manual review to detect and prevent abuse:</p>

        <h3>5.1 Automated Scanning</h3>
        <ul>
          <li>
            <strong>Real-time analysis:</strong> All links are scanned at creation time
          </li>
          <li>
            <strong>Malware detection:</strong> Integration with threat intelligence databases
          </li>
          <li>
            <strong>Phishing detection:</strong> Pattern matching and URL analysis
          </li>
          <li>
            <strong>Continuous monitoring:</strong> Links are periodically re-scanned
          </li>
        </ul>

        <h3>5.2 Intelligence Sources</h3>
        <p>We integrate with industry-standard threat intelligence sources, including:</p>
        <ul>
          <li>Google Safe Browsing</li>
          <li>PhishTank</li>
          <li>Cloudflare threat intelligence</li>
          <li>Community-reported threats</li>
        </ul>

        <h3>5.3 Detection Accuracy</h3>
        <p>
          While we strive for high accuracy, no automated system is perfect. If you believe a link
          was incorrectly flagged, please use our appeals process (Section 10).
        </p>
      </section>

      {/* Section 6: Spam Policy */}
      <section id="spam-policy">
        <h2>6. Spam Policy</h2>
        <p>{productName} must not be used to distribute spam or unsolicited commercial messages.</p>

        <h3>6.1 Definition of Spam</h3>
        <p>Spam includes but is not limited to:</p>
        <ul>
          <li>Unsolicited bulk emails containing {productName} links</li>
          <li>Mass messaging on social media platforms</li>
          <li>Comment spam on blogs, forums, or websites</li>
          <li>SMS spam or robocalls containing our links</li>
          <li>Pop-up or pop-under advertisements</li>
        </ul>

        <h3>6.2 Email Requirements</h3>
        <p>If you use {productName} links in email marketing:</p>
        <ul>
          <li>You must comply with CAN-SPAM, GDPR, and other applicable regulations</li>
          <li>Recipients must have opted in to receive your communications</li>
          <li>You must provide a working unsubscribe mechanism</li>
          <li>Your emails must include valid sender identification</li>
        </ul>

        <h3>6.3 Social Media</h3>
        <p>
          You must comply with the terms of service of any platform where you share
          {productName} links. Automated or excessive posting may trigger our abuse detection.
        </p>
      </section>

      {/* Section 7: Fair Use */}
      <section id="fair-use">
        <h2>7. Fair Use</h2>
        <p>
          All {productName} accounts are subject to fair use limits to ensure service quality for
          all users.
        </p>

        <h3>7.1 Usage Guidelines</h3>
        <ul>
          <li>Use the Service in a manner consistent with normal business operations</li>
          <li>Do not create an excessive number of links that are never used</li>
          <li>Respect API rate limits for your subscription tier</li>
          <li>Do not use the Service in ways that degrade performance for others</li>
        </ul>

        <h3>7.2 Resource Limits</h3>
        <p>
          Accounts that consistently consume excessive resources may be contacted to discuss
          upgrading to an appropriate plan or optimizing their usage.
        </p>

        <h3>7.3 Inactive Links</h3>
        <p>
          We reserve the right to deactivate links that have been inactive for extended periods on
          free accounts. We will provide notice before taking such action.
        </p>
      </section>

      {/* Section 8: Enforcement */}
      <section id="enforcement">
        <h2>8. Enforcement</h2>
        <p>
          We take a graduated approach to enforcement, with actions proportional to the severity and
          pattern of violations.
        </p>

        <h3>8.1 Link-Level Actions</h3>
        <ul>
          <li>
            <strong>Warning page:</strong> Users see a warning before proceeding to the destination
          </li>
          <li>
            <strong>Link disabled:</strong> The link is deactivated and returns an error
          </li>
          <li>
            <strong>Link deleted:</strong> The link is permanently removed from our system
          </li>
        </ul>

        <h3>8.2 Account-Level Actions</h3>
        <ul>
          <li>
            <strong>Warning:</strong> Notification of the violation with required corrective action
          </li>
          <li>
            <strong>Temporary suspension:</strong> Account access restricted for a period
          </li>
          <li>
            <strong>Permanent ban:</strong> Account terminated with no possibility of reinstatement
          </li>
        </ul>

        <h3>8.3 Immediate Termination</h3>
        <p>Certain violations result in immediate account termination without warning:</p>
        <ul>
          <li>Distribution of child sexual abuse material (CSAM)</li>
          <li>Malware distribution</li>
          <li>Phishing operations</li>
          <li>Terrorism-related content</li>
          <li>Repeated violations after warnings</li>
        </ul>

        <h3>8.4 Cooperation with Authorities</h3>
        <p>
          We cooperate with law enforcement agencies and may report illegal activity. We are
          required to report CSAM to the National Center for Missing &amp; Exploited Children
          (NCMEC) and relevant authorities.
        </p>
      </section>

      {/* Section 9: Reporting Abuse */}
      <section id="reporting">
        <h2>9. Reporting Abuse</h2>
        <p>We encourage users and the public to report suspected policy violations.</p>

        <h3>9.1 How to Report</h3>
        <p>You can report abusive links or accounts by:</p>
        <ul>
          <li>
            <strong>Email:</strong> <a href="mailto:abuse@go2.gg">abuse@go2.gg</a>
          </li>
          <li>
            <strong>Report form:</strong> Available on our warning pages when you encounter a
            flagged link
          </li>
          <li>
            <strong>API:</strong> Enterprise customers can use our abuse reporting API
          </li>
        </ul>

        <h3>9.2 What to Include</h3>
        <p>When reporting, please include:</p>
        <ul>
          <li>The {productName} short link URL (e.g., go2.gg/abc123)</li>
          <li>Description of the violation</li>
          <li>Any evidence (screenshots, emails, etc.)</li>
          <li>Your contact information (optional but helpful)</li>
        </ul>

        <h3>9.3 Response Time</h3>
        <p>
          We review all abuse reports within 24 hours. Critical reports (CSAM, active phishing) are
          prioritized and typically addressed within 1 hour.
        </p>

        <h3>9.4 Confidentiality</h3>
        <p>
          Reporter information is kept confidential and not shared with the reported party unless
          required by law.
        </p>
      </section>

      {/* Section 10: Appeals */}
      <section id="appeals">
        <h2>10. Appeals Process</h2>
        <p>
          If you believe an enforcement action was taken in error, you have the right to appeal.
        </p>

        <h3>10.1 How to Appeal</h3>
        <p>
          Submit an appeal to <a href="mailto:appeals@go2.gg">appeals@go2.gg</a> with:
        </p>
        <ul>
          <li>Your account email or the affected link URL</li>
          <li>Explanation of why you believe the action was incorrect</li>
          <li>Any supporting evidence</li>
        </ul>

        <h3>10.2 Appeal Timeline</h3>
        <ul>
          <li>Appeals must be submitted within 30 days of the enforcement action</li>
          <li>We will review and respond within 7 business days</li>
          <li>Complex cases may require additional time</li>
        </ul>

        <h3>10.3 Appeal Outcomes</h3>
        <ul>
          <li>
            <strong>Upheld:</strong> The original decision stands
          </li>
          <li>
            <strong>Overturned:</strong> The action is reversed and access restored
          </li>
          <li>
            <strong>Modified:</strong> The action is changed to a lesser enforcement
          </li>
        </ul>

        <h3>10.4 Final Decision</h3>
        <p>
          Our decision on appeal is final. Repeated frivolous appeals may be considered harassment
          and result in additional enforcement action.
        </p>
      </section>

      {/* Section 11: Contact */}
      <section id="contact">
        <h2>11. Contact Us</h2>
        <p>For questions about this Acceptable Use Policy:</p>
        <ul>
          <li>
            <strong>General inquiries:</strong>{" "}
            <a href={`mailto:${contactEmail}`}>{contactEmail}</a>
          </li>
          <li>
            <strong>Abuse reports:</strong> <a href="mailto:abuse@go2.gg">abuse@go2.gg</a>
          </li>
          <li>
            <strong>Appeals:</strong> <a href="mailto:appeals@go2.gg">appeals@go2.gg</a>
          </li>
          <li>
            <strong>Security issues:</strong> <a href="mailto:security@go2.gg">security@go2.gg</a>
          </li>
        </ul>
        <p>This policy is subject to change. Please review it periodically for updates.</p>
      </section>
    </LegalPageTemplate>
  );
}
