-- Migration: Agent Attribution
-- Created: 2026-04-27
--
-- Adds agent-context fields to `links` and `clicks` so that links generated by
-- AI agents (Claude Code, Cursor, OpenAI Assistants, MCP clients, etc.) can be
-- attributed back to a specific agent run / tool call / human actor at click time.
--
-- Fields are namespaced with `agent_` to avoid collisions with UTM/AB/conversion
-- fields. All fields are nullable — existing non-agent links keep working.

-- Links table: who created this link?
ALTER TABLE `links` ADD COLUMN `agent_id` text;
ALTER TABLE `links` ADD COLUMN `agent_run_id` text;
ALTER TABLE `links` ADD COLUMN `agent_actor_id` text;
ALTER TABLE `links` ADD COLUMN `agent_metadata` text; -- JSON blob, free-form

CREATE INDEX IF NOT EXISTS `links_agent_id_idx` ON `links` (`agent_id`);
CREATE INDEX IF NOT EXISTS `links_agent_run_id_idx` ON `links` (`agent_run_id`);

-- Clicks table: who/what generated this click?
-- Populated from the link's defaults at click time AND/OR overridden by query
-- params (?ag=, ?ar=, ?at=, ?au=) or x-agent-* request headers.
ALTER TABLE `clicks` ADD COLUMN `agent_id` text;
ALTER TABLE `clicks` ADD COLUMN `agent_run_id` text;
ALTER TABLE `clicks` ADD COLUMN `agent_actor_id` text;
ALTER TABLE `clicks` ADD COLUMN `agent_tool_call_id` text;

CREATE INDEX IF NOT EXISTS `clicks_agent_id_idx` ON `clicks` (`agent_id`);
CREATE INDEX IF NOT EXISTS `clicks_agent_run_id_idx` ON `clicks` (`agent_run_id`);
